# Generated by Django 5.1.1 on 2024-10-10 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
        ('Persona', '0002_alter_persona_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'Profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Persona.persona'),
        ),
    ]
