# Generated by Django 5.1.1 on 2024-10-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstudiantesCursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('costo', models.FloatField()),
                ('estudianteCurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstudiantesCursos.estudiantescursos', verbose_name='ID de EstudianteCurso')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
    ]
