# Generated by Django 5.1.1 on 2024-10-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0002_alter_curso_profesor'),
        ('Persona', '0002_alter_persona_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantesCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('estado', models.CharField(max_length=50)),
                ('nota_final', models.FloatField()),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.curso', verbose_name='ID del Curso')),
                ('estudiante_id', models.ForeignKey(limit_choices_to={'rol': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, to='Persona.persona', verbose_name='ID del Estudiante')),
            ],
            options={
                'db_table': 'EstudiantesCursos',
            },
        ),
    ]
